import ProjectExplorer from "./ProjectExplorer";

export const metadata = {
  title: "Our Projects — Bharath Solar EPC",
  description:
    "Explore Bharath Solar EPC's marquee installations across industrial, healthcare, education and commercial partners in an interactive showcase.",
};

const CURRENT_YEAR = new Date().getFullYear();

const PROJECTS = [
  {
    client: "Regenesis Industries Pvt Ltd",
    location: "Bommalaramaram",
    sector: "Industrial Manufacturing",
    capacityKw: 300,
    count: 1,
    capacityLabel: "300 kW rooftop",
    timeline: "Commissioned 2018",
    yearStart: 2018,
    yearEnd: 2018,
    tags: ["regenesis", "bommalaramaram", "industrial"],
  },
  {
    client: "Regenesis Industries Pvt Ltd",
    location: "Bommalaramaram",
    sector: "Industrial Manufacturing",
    capacityKw: 600,
    count: 1,
    capacityLabel: "600 kW rooftop",
    timeline: "Commissioned 2022",
    yearStart: 2022,
    yearEnd: 2022,
    tags: ["regenesis", "bommalaramaram", "expansion"],
  },
  {
    client: "Salvo Explosives & Chemicals Pvt Ltd",
    location: "Ankireddy Palli",
    sector: "Industrial Manufacturing",
    capacityKw: 500,
    count: 1,
    capacityLabel: "500 kW rooftop",
    timeline: "Commissioned 2020",
    yearStart: 2020,
    yearEnd: 2020,
    tags: ["salvo", "explosives"],
  },
  {
    client: "Salvo Explosives & Chemicals Pvt Ltd",
    location: "Ankireddy Palli",
    sector: "Industrial Manufacturing",
    capacityKw: 50,
    count: 1,
    capacityLabel: "50 kW rooftop",
    timeline: "Commissioned 2020",
    yearStart: 2020,
    yearEnd: 2020,
    tags: ["salvo", "expansion", "modular"],
  },
  {
    client: "Ideal Industrial Explosives Ltd",
    location: "Chityala",
    sector: "Industrial Manufacturing",
    capacityKw: 250,
    count: 1,
    capacityLabel: "250 kW rooftop",
    timeline: "Commissioned 2019",
    yearStart: 2019,
    yearEnd: 2019,
    tags: ["ideal", "chityala"],
  },
  {
    client: "Ideal Industrial Explosives Ltd",
    location: "Chityala",
    sector: "Industrial Manufacturing",
    capacityKw: 160,
    count: 1,
    capacityLabel: "160 kW rooftop",
    timeline: "Commissioned 2022",
    yearStart: 2022,
    yearEnd: 2022,
    tags: ["ideal", "chityala", "upgrade"],
  },
  {
    client: "Ideal Industrial Explosives Ltd",
    location: "Kothagudem",
    sector: "Industrial Manufacturing",
    capacityKw: 60,
    count: 1,
    capacityLabel: "60 kW rooftop",
    timeline: "Commissioned 2023",
    yearStart: 2023,
    yearEnd: 2023,
    tags: ["ideal", "kothagudem"],
  },
  {
    client: "JV Poultry Farms",
    location: "Telangana",
    sector: "Agri & Food Processing",
    capacityKw: 100,
    count: 1,
    capacityLabel: "100 kW ground mount",
    timeline: "Commissioned 2023",
    yearStart: 2023,
    yearEnd: 2023,
    tags: ["poultry", "agriculture"],
  },
  {
    client: "Valigonda Community Solar",
    location: "Nalgonda District",
    sector: "Community & Public",
    capacityKw: 100,
    count: 1,
    capacityLabel: "100 kW distributed",
    timeline: "Commissioned 2024",
    yearStart: 2024,
    yearEnd: 2024,
    tags: ["valigonda", "nalgonda"],
  },
  {
    client: "Nithisha Poultry Farms",
    location: "Gandicheruvu",
    sector: "Agri & Food Processing",
    capacityKw: 100,
    count: 1,
    capacityLabel: "100 kW rooftop",
    timeline: "Commissioned 2024",
    yearStart: 2024,
    yearEnd: 2024,
    tags: ["poultry", "gandicheruvu"],
  },
  {
    client: "Tulasi Hospitals",
    location: "ECIL Cross Roads",
    sector: "Healthcare",
    capacityKw: 120,
    count: 1,
    capacityLabel: "120 kW rooftop",
    timeline: "Commissioned 2018",
    yearStart: 2018,
    yearEnd: 2018,
    tags: ["hospital", "ecil"],
  },
  {
    client: "Samskruti College of Engineering",
    location: "Ghatkesar",
    sector: "Education",
    capacityKw: 70,
    count: 1,
    capacityLabel: "70 kW rooftop",
    timeline: "Commissioned 2017",
    yearStart: 2017,
    yearEnd: 2017,
    tags: ["college", "ghatkesar"],
  },
  {
    client: "Sri Indu Engineering College",
    location: "Mangalpalli",
    sector: "Education",
    capacityKw: 50,
    count: 1,
    capacityLabel: "50 kW rooftop",
    timeline: "Commissioned 2019",
    yearStart: 2019,
    yearEnd: 2019,
    tags: ["college", "mangalpalli"],
  },
  {
    client: "Radhika Multi Speciality Hospital",
    location: "Balapur",
    sector: "Healthcare",
    capacityKw: 40,
    count: 1,
    capacityLabel: "40 kW rooftop",
    timeline: "Commissioned 2020",
    yearStart: 2020,
    yearEnd: 2020,
    tags: ["hospital", "balapur"],
  },
  {
    client: "Nightingale Hospital",
    location: "Telangana",
    sector: "Healthcare",
    capacityKw: 30,
    count: 1,
    capacityLabel: "30 kW rooftop",
    timeline: "Commissioned 2016",
    yearStart: 2016,
    yearEnd: 2016,
    tags: ["hospital"],
  },
  {
    client: "Kavya Medicare",
    location: "Balapur",
    sector: "Healthcare",
    capacityKw: 10,
    count: 1,
    capacityLabel: "10 kW rooftop",
    timeline: "Commissioned 2020",
    yearStart: 2020,
    yearEnd: 2020,
    tags: ["clinic", "balapur"],
  },
  {
    client: "Hotel Ridhika Inn",
    location: "Suryapet",
    sector: "Hospitality",
    capacityKw: 40,
    count: 1,
    capacityLabel: "40 kW rooftop",
    timeline: "Commissioned 2022",
    yearStart: 2022,
    yearEnd: 2022,
    tags: ["hotel", "suryapet"],
  },
  {
    client: "Darwin Ayur Pharma",
    location: "Vijayawada",
    sector: "Life Sciences & Pharma",
    capacityKw: 40,
    count: 1,
    capacityLabel: "40 kW rooftop",
    timeline: "Commissioned 2020",
    yearStart: 2020,
    yearEnd: 2020,
    tags: ["pharma", "vijayawada"],
  },
  {
    client: "Ratna Hospital",
    location: "IS Sadan",
    sector: "Healthcare",
    capacityKw: 20,
    count: 1,
    capacityLabel: "20 kW rooftop",
    timeline: "Commissioned 2017",
    yearStart: 2017,
    yearEnd: 2017,
    tags: ["hospital", "is sadan"],
  },
  {
    client: "Srinivasa Junior College",
    location: "IS Sadan",
    sector: "Education",
    capacityKw: 20,
    count: 1,
    capacityLabel: "20 kW rooftop",
    timeline: "Commissioned 2019",
    yearStart: 2019,
    yearEnd: 2019,
    tags: ["college", "is sadan"],
  },
  {
    client: "Distributed On-Grid Customers",
    location: "Across Telangana",
    sector: "Residential & MSME",
    capacityKw: 10,
    count: 5,
    capacityLabel: "5 × 10 kW on-grid systems",
    timeline: "2016 – Till Date",
    yearStart: 2016,
    yearEnd: CURRENT_YEAR,
    tags: ["distributed", "on-grid"],
  },
  {
    client: "Distributed Off-Grid Customers",
    location: "Across Telangana",
    sector: "Rural & Off-grid",
    capacityKw: 1,
    count: 80,
    capacityLabel: "80 × 1 kW off-grid systems",
    timeline: "2017 – Till Date",
    yearStart: 2017,
    yearEnd: CURRENT_YEAR,
    tags: ["off-grid", "rural"],
  },
  {
    client: "Residential Customers",
    location: "Across Telangana",
    sector: "Residential & MSME",
    capacityKw: 2,
    count: 134,
    capacityLabel: "134 × 2 kW systems",
    timeline: "2015 – Till Date",
    yearStart: 2015,
    yearEnd: CURRENT_YEAR,
    tags: ["residential", "distributed"],
  },
  {
    client: "Small Commercial Customers",
    location: "Across Telangana",
    sector: "Commercial & Retail",
    capacityKw: 3,
    count: 58,
    capacityLabel: "58 × 3 kW systems",
    timeline: "2015 – Till Date",
    yearStart: 2015,
    yearEnd: CURRENT_YEAR,
    tags: ["commercial", "distributed"],
  },
  {
    client: "Growing SME Customers",
    location: "Across Telangana",
    sector: "Commercial & Retail",
    capacityKw: 5,
    count: 26,
    capacityLabel: "26 × 5 kW systems",
    timeline: "2016 – Till Date",
    yearStart: 2016,
    yearEnd: CURRENT_YEAR,
    tags: ["sme", "distributed"],
  },
];

export default function ProjectsPage() {
  return <ProjectExplorer projects={PROJECTS} />;
}
